// ============================================================
//  Alphabet World — Letter personality system
//  هر حرف یک شخصیت مستقل دارد. زبان توضیحات دوزبانه است.
// ============================================================

import type { LetterProfile } from "./types";

const HUES = {
  coral: "#E8825A",
  amber: "#E0A458",
  gold: "#D9B24C",
  sage: "#6B9080",
  teal: "#5C9EAD",
  sky: "#6E92C7",
  plum: "#9D7BB0",
  rose: "#D3728E",
  clay: "#C77B58",
  moss: "#8AA35B",
  slate: "#7C8AA0",
  berry: "#B85C7A",
} as const;

export const LETTERS: LetterProfile[] = [
  { char: "A", hue: HUES.coral, trait: "leader",
    personality: { fa: "مطمئن و همیشه در حرکت. رهبر گروه.", de: "Selbstbewusst und immer in Bewegung. Der Anführer." },
    idle: ["walk", "jump", "bounce"] },
  { char: "B", hue: HUES.amber, trait: "social",
    personality: { fa: "اجتماعی و دوستانه — به همه سلام می‌کند.", de: "Freundlich und sozial — winkt jedem zu." },
    idle: ["walk", "wiggle", "play"] },
  { char: "C", hue: HUES.gold, trait: "curious",
    personality: { fa: "کنجکاو و کمی خجالتی، برای فکر کردن مارپیچ می‌شود.", de: "Neugierig und etwas schüchtern, rollt sich zum Denken zusammen." },
    idle: ["ponder", "walk", "sleep"] },
  { char: "D", hue: HUES.sage, trait: "calm",
    personality: { fa: "آرام و قابل اعتماد. به‌ندرت عجله می‌کند.", de: "Ruhig und verlässlich. Selten in Eile." },
    idle: ["walk", "ponder"] },
  { char: "E", hue: HUES.teal, trait: "popular",
    personality: { fa: "محبوب‌ترین حرف — همه را از نزدیک می‌شناسد.", de: "Der bekannteste Buchstabe — kennt jeden beim Namen." },
    idle: ["walk", "wiggle", "jump"] },
  { char: "F", hue: HUES.sky, trait: "dreamer",
    personality: { fa: "رویاپرداز ته‌خط، همیشه به افق می‌رسد.", de: "Verträumter Wanderer, immer dem Horizont entgegen." },
    idle: ["wander", "ponder"] },
  { char: "G", hue: HUES.plum, trait: "moody",
    personality: { fa: "صبح‌ها بداخلاق، بعدازظهرها شوخ‌طبع.", de: "Morgens mürrisch, nachmittags verspielt." },
    idle: ["sleep", "walk", "play"] },
  { char: "H", hue: HUES.rose, trait: "helpful",
    personality: { fa: "مهربان و کمک‌کننده، در را برای دیگران نگه می‌دارد.", de: "Hilfsbereit und warmherzig, hält anderen die Tür auf." },
    idle: ["walk", "wiggle"] },
  { char: "I", hue: HUES.clay, trait: "dot-lover",
    personality: { fa: "عاشق نقطه‌اش — دائماً آن را چک می‌کند.", de: "Versessen auf seinen Punkt — prüft ständig nach ihm." },
    idle: ["bounce", "wiggle", "ponder"] },
  { char: "J", hue: HUES.moss, trait: "bouncy",
    personality: { fa: "شاد و پرانرژی، عاشق نقطه‌اش است.", de: "Federnd und fröhlich, liebt seinen Punkt auch." },
    idle: ["jump", "bounce"] },
  { char: "K", hue: HUES.slate, trait: "clever",
    personality: { fa: "تیز و باهوش، همیشه برنامه‌ای دارد.", de: "Scharfsinnig und clever, hat immer einen Plan." },
    idle: ["walk", "spin"] },
  { char: "L", hue: HUES.berry, trait: "relaxed",
    personality: { fa: "آسوده و کش‌دار، به بقیه تکیه می‌کند.", de: "Entspannt und lang, lehnt sich an die anderen." },
    idle: ["ponder", "walk", "sleep"] },
  { char: "M", hue: HUES.coral, trait: "caring",
    personality: { fa: "مادرانه — همیشه از همه حساب می‌کشد.", de: "Mütterlich — behält alle im Blick." },
    idle: ["walk", "wiggle"] },
  { char: "N", hue: HUES.amber, trait: "twin",
    personality: { fa: "همزاد M، حرف‌های M را تمام می‌کند.", de: "Ms Zwilling, beendet Ms Sätze." },
    idle: ["walk", "wiggle"] },
  { char: "O", hue: HUES.gold, trait: "roller",
    personality: { fa: "کاملاً گرد و کاملاً آرام. می‌غلتد، راه نمی‌رود.", de: "Perfekt rund und perfekt entspannt. Rollt, geht nie." },
    idle: ["spin", "bounce", "sleep"] },
  { char: "P", hue: HUES.sage, trait: "proud",
    personality: { fa: "مغرور و باوقار، زیاد ژست می‌گیرد.", de: "Stolz und wohlgewählt, posiert oft." },
    idle: ["walk", "spin"] },
  { char: "Q", hue: HUES.teal, trait: "seeks-U",
    personality: { fa: "مدام دنبال U می‌گردد. جستجو را ول نمی‌کند.", de: "Sucht ständig nach U. Hört nie auf zu suchen." },
    idle: ["wander", "ponder"] },
  { char: "R", hue: HUES.sky, trait: "dramatic",
    personality: { fa: "صداهایش و بدنش می‌غلتند — بسیار تئاتری.", de: "Rollen seine Laute und sein Körper — sehr theatralisch." },
    idle: ["spin", "walk", "jump"] },
  { char: "S", hue: HUES.plum, trait: "smooth",
    personality: { fa: "لغزنده و نرم، همه‌جا می‌لغزد.", de: "Rutschig und glatt, gleitet überall hin." },
    idle: ["wander", "wiggle"] },
  { char: "T", hue: HUES.rose, trait: "tidy",
    personality: { fa: "قدبلند، آرام و کمی سخت‌گیر درباره ترتیب.", de: "Groß, ruhig und etwas streng bei Ordnung." },
    idle: ["walk", "ponder"] },
  { char: "U", hue: HUES.clay, trait: "avoids-Q",
    personality: { fa: "مهربان، ولی گاهی برای شوخی از Q قایم می‌شود.", de: "Lieb, versteckt sich aber gern mal vor Q zum Spaß." },
    idle: ["walk", "play", "sleep"] },
  { char: "V", hue: HUES.moss, trait: "explorer",
    personality: { fa: "ماجراجو، همیشه به جای جدیدی اشاره می‌کند.", de: "Abenteuerlustig, zeigt immer woanders hin." },
    idle: ["wander", "jump"] },
  { char: "W", hue: HUES.slate, trait: "chatty",
    personality: { fa: "همزاد پرحرف V. دو برابر حرف می‌زند.", de: "Vs geschwätziger Doppelgänger. Redet doppelt so viel." },
    idle: ["wiggle", "walk"] },
  { char: "X", hue: HUES.berry, trait: "rare",
    personality: { fa: "مرموز و کمیاب، بیشتر تنهاست.", de: "Geheimnisvoll und selten, hält sich meist für sich." },
    idle: ["sleep", "ponder"] },
  { char: "Y", hue: HUES.coral, trait: "thinker",
    personality: { fa: "از همه می‌پرسد — یک فیلسوف مهربان.", de: "Hinterfragt alles — ein sanfter Philosoph." },
    idle: ["ponder", "wander"] },
  { char: "Z", hue: HUES.amber, trait: "sleepy",
    personality: { fa: "خواب‌آلود و کند — zzz صدای مورد علاقه‌اش است.", de: "Schläfrig und langsam — zzz ist sein Lieblingslaut." },
    idle: ["sleep", "walk"] },
  // ---- حروف خاص آلمانی — شهروند درجه یک ----
  { char: "Ä", hue: HUES.teal, trait: "umlaut",
    personality: { fa: "با دو نقطه اوملوتش بازی می‌کند.", de: "Spielt Fangen mit seinen zwei Umlaut-Punkten." },
    idle: ["play", "bounce", "jump"] },
  { char: "Ö", hue: HUES.plum, trait: "umlaut",
    personality: { fa: "همین‌که می‌غلتد، نقطه‌هایش را ژانگ می‌اندازد.", de: "Jongliert mit seinen Punkten beim Rollen." },
    idle: ["spin", "play", "bounce"] },
  { char: "Ü", hue: HUES.rose, trait: "umlaut",
    personality: { fa: "نقطه‌هایش را بالا پرت می‌کند و می‌گیرد.", de: "Wirft seine Punkte hoch und fängt sie wieder." },
    idle: ["play", "jump", "wiggle"] },
  { char: "ß", hue: HUES.berry, trait: "mischief",
    personality: { fa: "کمی شیطان و غیرعادی — همان S تیز است.", de: "Ein bisschen frech und ungewöhnlich — das scharfe S." },
    idle: ["wiggle", "spin", "play"] },
];

export function buildProfileMap(): Map<string, LetterProfile> {
  const map = new Map<string, LetterProfile>();
  for (const l of LETTERS) map.set(l.char, l);
  return map;
}
